//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::StatusEnum;
use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "booking")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub room_id: Uuid,
    pub starts_at: DateTime,
    pub ends_at: DateTime,
    pub status: StatusEnum,
    pub checked_in: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(ignore, column_type = "custom(\"tstzrange\")", select_as = "text")]
    #[serde(skip)]
    pub time_slot: String,
    #[sea_orm(has_many)]
    #[serde(skip)]
    pub reminders: HasMany<super::reminder::Entity>,
    #[sea_orm(
        belongs_to,
        from = "room_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    #[serde(skip)]
    pub room: HasOne<super::room::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    #[serde(skip)]
    pub user: HasOne<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
