//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::ChannelEnum;
use super::sea_orm_active_enums::StatEnum;
use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "reminder")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub booking_id: Uuid,
    pub channel: ChannelEnum,
    pub scheduled_for: DateTime,
    pub sent_at: DateTime,
    pub status: StatEnum,
    #[sea_orm(column_type = "Text")]
    pub failure_reason: String,
    pub created_at: DateTime,
    #[sea_orm(
        belongs_to,
        from = "booking_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    #[serde(skip)]
    pub booking: HasOne<super::booking::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
