//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "room_time_slots")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub room_id: Uuid,
    #[sea_orm(ignore, column_type = "custom(\"tstzrange\")", select_as = "text")]
    #[serde(skip)]
    pub time_slot: String,
    #[sea_orm(
        belongs_to,
        from = "room_id",
        to = "id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    #[serde(skip)]
    pub room: HasOne<super::room::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
