//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize)]
#[sea_orm(table_name = "room")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub room_code: String,
    pub room_name: String,
    #[sea_orm(column_type = "Text")]
    pub location: String,
    pub capacity: i32,
    #[sea_orm(column_type = "Text")]
    pub usage_notes: String,
    pub is_active: bool,
    pub created_at: DateTime,
    #[sea_orm(has_many)]
    #[serde(skip)]
    pub bookings: HasMany<super::booking::Entity>,
    #[sea_orm(has_many)]
    #[serde(skip)]
    pub room_time_slots: HasMany<super::room_time_slots::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
